# Enable more optional rules
opt_in_rules:
  - implicit_return
  - let_var_whitespace
  - unneeded_parentheses_in_closure_argument
  - closure_spacing
  - explicit_init
  - overridden_super_call
  - closure_end_indentation
  - empty_count
  - fatal_error_message
  - force_unwrapping
  - force_try
  - force_cast
  - switch_case_on_newline
  - redundant_nil_coalescing
  - prohibited_super_call
  - operator_usage_whitespace
  - number_separator
  - nimble_operator
  - implicitly_unwrapped_optional
  - attributes
  - first_where
  - multiline_parameters
  - multiline_arguments
  - discouraged_optional_collection
  - discouraged_optional_boolean
  - trailing_closure
  - vertical_parameter_alignment_on_call
  - no_fallthrough_only
  - file_name
  - empty_xctest_method
  - convenience_type
  - anyobject_protocol
  - legacy_random
  - closure_body_length
  - inert_defer
  - toggle_bool
  - identical_operands
  - collection_alignment
  - static_operator

# Exclude pods and vendor sources
excluded:
  - Pods
  - Carthage
  - ./*/SnapshotHelper.swift

# Configure warning/error levels
file_length:
  warning: 450
  error: 500
function_body_length:
  warning: 100
  error: 150
function_parameter_count:
  warning: 9
  error: 10
line_length:
  warning: 120
  error: 250
  ignores_function_declarations: true
  ignores_comments: true
  ignores_interpolated_strings: true
  ignores_urls: true
identifier_name:
  max_length:
    warning: 45
    error: 60
  min_length:
    warning: 1
type_name:
  max_length:
    warning: 40
    error: 70
  min_length:
    warning: 3

# Configure rules violation to be treated as an error
explicit_init:
  severity: error
prohibited_super_call:
  severity: error
overridden_super_call:
  severity: error
force_unwrapping:
  severity: error
weak_delegate:
  severity: error
multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true
