platform :ios, '10.0'
use_frameworks!
inhibit_all_warnings!

target 'DocumentScannerApp' do
  pod 'DocumentScanner', :path => '../'
  pod 'TOCropViewController'
  pod 'SwiftLint'

  target 'DocumentScannerAppTests' do
    inherit! :search_paths
  end
end
