language: swift
osx_image: xcode10
env: LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 

before_install:
  - gem update --system
  - gem install bundler
install:
  - bundle install
script:
  - bundle exec fastlane analyze
