name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Gem Dependencies
      run: bundle install
    - name: Run Fastlane Analyze
      run: bundle exec fastlane analyze
